apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-action-pro-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-action-pro
  template:
    metadata:
      labels:
        app: github-action-pro
    spec:
      containers:
        - name: github-action-pro
          image: 228948463033.dkr.ecr.us-east-1.amazonaws.com/github_action_pro:latest
          ports:
            - containerPort: 5000
