apiVersion: v1
kind: Service
metadata:
  name: github-action-pro-service
spec:
  type: LoadBalancer
  selector:
    app: github-action-pro
  ports:
    - port: 80          # Public port
      targetPort: 5000  # Container port
