name: Build, Push & Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials (must match aws-auth mapUsers)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t github_action_pro .

      # Step 5: Tag Docker image for ECR
      - name: Tag Docker image
        run: docker tag github_action_pro:latest 228948463033.dkr.ecr.us-east-1.amazonaws.com/github_action_pro:latest

      # Step 6: Push Docker image to ECR
      - name: Push Docker image
        run: docker push 228948463033.dkr.ecr.us-east-1.amazonaws.com/github_action_pro:latest

      # Step 7: Deploy to EKS
      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name ECR-cluster
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
